version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/gcc:14.0
    steps:
      - checkout
      - run:
          name: Ensure full repository clone
          command: git fetch --unshallow
      - run:
          name: Debug file structure
          command: |
            echo "Listing files:"
            ls -R
            echo "Checking 6th_week/bptree contents:"
            ls -R 6th_week/bptree
      - run:
          name: Ensure deploy.sh is executable
          command: chmod +x ./deploy.sh
      - run:
          name: Run deploy script
          - add_ssh_keys:
            fingerprints:
              - "SHA256:zs+bHZTFHdV9DCwFvfad+2FZQP10V8ZiIMz/fWCN8AM"
          command: |
            sh ./deploy.sh || (echo "Deploy script failed!" && exit 1)

workflows:
  Deploy-Workflow:
    jobs:
      - deploy
